DELETE FROM APARTMENT;

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (1, TRUE, 120, FALSE, 2, 3, 'Furnished', FALSE, TRUE, TRUE, TRUE, 1, TRUE, 85000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (2, FALSE, 90, FALSE, 1, 2, 'Semi-Furnished', FALSE, TRUE, TRUE, FALSE, 1, FALSE, 60000, 1, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (3, TRUE, 150, TRUE, 3, 4, 'Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 120000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (4, FALSE, 80, FALSE, 1, 2, 'Unfurnished', FALSE, FALSE, TRUE, FALSE, 0, FALSE, 50000, 1, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (5, TRUE, 200, TRUE, 3, 5, 'Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 160000, 3, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (6, TRUE, 110, FALSE, 2, 3, 'Semi-Furnished', FALSE, TRUE, TRUE, TRUE, 1, FALSE, 78000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (7, FALSE, 95, FALSE, 1, 2, 'Unfurnished', FALSE, FALSE, TRUE, FALSE, 1, FALSE, 55000, 1, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (8, TRUE, 140, TRUE, 2, 4, 'Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 110000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (9, FALSE, 100, FALSE, 2, 3, 'Semi-Furnished', FALSE, TRUE, TRUE, TRUE, 1, FALSE, 70000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (10, TRUE, 180, TRUE, 3, 4, 'Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 145000, 3, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (11, TRUE, 130, FALSE, 2, 3, 'Furnished', FALSE, TRUE, TRUE, TRUE, 1, TRUE, 90000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (12, FALSE, 85, FALSE, 1, 2, 'Unfurnished', FALSE, FALSE, TRUE, FALSE, 0, FALSE, 48000, 1, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (13, TRUE, 160, TRUE, 3, 4, 'Semi-Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 125000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (14, FALSE, 105, FALSE, 2, 3, 'Semi-Furnished', FALSE, TRUE, TRUE, TRUE, 1, FALSE, 73000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (15, TRUE, 190, TRUE, 3, 5, 'Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 155000, 3, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (16, TRUE, 115, FALSE, 2, 3, 'Furnished', FALSE, TRUE, TRUE, TRUE, 1, TRUE, 82000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (17, FALSE, 92, FALSE, 1, 2, 'Unfurnished', FALSE, FALSE, TRUE, FALSE, 1, FALSE, 56000, 1, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (18, TRUE, 145, TRUE, 2, 4, 'Semi-Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 108000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (19, FALSE, 98, FALSE, 2, 3, 'Semi-Furnished', FALSE, TRUE, TRUE, TRUE, 1, FALSE, 69000, 2, NULL);

INSERT INTO APARTMENT (
    ID_APARTMENT, AIRCONDITIONING, AREA, BASEMENT, BATHROOMS, BEDROOMS,
    FURNISHINGSTATUS, GUESTROOM, HEATING, HOTWATER, MAINROAD,
    PARKING, PREFAREA, PRICE, STORIES, ID_PERSON
) VALUES (20, TRUE, 170, TRUE, 3, 4, 'Furnished', TRUE, TRUE, TRUE, TRUE, 2, TRUE, 138000, 3, NULL);
